external-secrets/kubernetes-external-secrets

README.md, lib/backends/kv-backend.js, lib/backends/kv-backend.test.js, lib/backends/secrets-manager-backend.js, lib/poller.js
This is useful (required?) to safely rotate secrets atomically, like a client
certificate and private key.
=> feat(json): support JSON objects in AWS Secret Manager

lib/poller.js, lib/poller.test.js
PATCH is going to result in a merge, potentially resulting in a union of the
previous Secret's fields and the updated Secret's fields.
=> fix(updating): use PUT not PATCH when updating an existing Secret

config/environment.js, config/index.js
This address https://github.com/godaddy/kubernetes-external-secrets/issues/51
Removing "hardcoded" aws default region in favor of using default behavior of AWS SDK.
=> fix(config): remove default aws region

lib/backends/kv-backend.js, lib/backends/kv-backend.test.js, lib/backends/secrets-manager-backend.js
See https://github.com/godaddy/kubernetes-external-secrets/issues/73 for
discussion.
=> fix(AWSSM): treat value as object iff the es specifies .property

README.md, config/aws-config.js, config/index.js, package.json
Add support for launching and connecting to localstack
=> feat(localstack): add support for running with localstack

lib/backends/kv-backend.js, lib/poller.js
The polling function was not outputting an error message when a property is missing from a secret. This addresses #63 .
=> Show error on missing property

external-secrets.yml
This needs a few improvements to be ready for prime time. See discussion in:
https://github.com/godaddy/kubernetes-external-secrets/issues/89
=> chore(kubectl): bring back the external-secrets.yml file

lib/daemon.js, lib/poller.js, lib/poller.test.js
Fixes #93
Not sure how you would like it configureable and what kind of defaults?
Figured I'd just draft a PR first 😄 
Im abit unsure about whether I plugged it in, in the right place. Seeing how `secretDescriptors` is an array being sent around, but its always just one?
I could add the ownerReference into the `secretDescriptor` object (https://github.com/godaddy/kubernetes-external-secrets/pull/95/files#diff-5c2754430010d5f3e95b45e1bb36d58bR55) but it feels weird to put it in there as well as its just some metadata and not part of the secretDescriptor
=> Add ownerreference to remove created secret when external secret is removed

lib/backends/kv-backend.js
If one misconfigures a secret these can end up in logs, which could be quite a hassle :)
Example:
```yaml
...
secretDescriptor:
backendType: secretsManager
data:
- key: hello-service/credentials
property: password
name: password
```
hello-service/credentials from secrets manager:
```js
{
"Name": "hello-service/credentials",
"SecretString": "my-super-secret-password",
...
}
```
Would log the following 
```
Failed to JSON.parse 'my-super-secret-password': {}
```
=> fix: remove logging of potentially secret value

lib/daemon.js, lib/poller.js, lib/poller.test.js
Make it clear that there's a 1:1 mapping between a `Poller` and an
ExternalSecret.
Both files could use another refactor pass.
=> refactor: poller.js and daemon.js

bin/daemon.js, config/environment.js, config/index.js, lib/daemon.js, lib/external-secret.js, lib/external-secret.test.js, lib/poller.js, lib/poller.test.js, package.json
Currently you can't set a lower events interval than poll interval, as this would result in never polling anything as the poller would be recreated everytime the events are polled.
Not sure if this is the best way to go about it but I tested refactoring so the events poller tracks which external secrets it has seen and yields appropriate events instead of always doing a delete all.
It would be nice if we could in some way instantly poll if an external secret has been modified or added. As if you have a long poll time you would currently have to wait for that to trigger, which feels slow when adding a new external secret. Not sure how to deal with pod restarts tho, as you wouldn't necessarily want to poll instantly when that happens, one alternative would be for the poller to check if the …
=> refactor: use watch api and instant poll new or modified secrets

lib/daemon.js
we have noticed that if we set POLLER_INTERVAL_MILLISECONDS=86400000 (24 hours) external secrets are not pulled from aws secrets manager and upserted to secrets immediately after deployment
=> Upsert secrets immediately for the first time #117 

examples/dockerconfig-example.yml, examples/tls-example.yml, lib/poller.js, lib/poller.test.js
Possible solution for #109 
> Does this require anything more than being able to set type in the external secret resource?
> 
> Example:
> 
> ```yaml
> apiVersion: kubernetes-client.io/v1
> kind: ExternalSecret
> metadata:
>   name: my-dockerhub-secret
> secretDescriptor:
>   backendType: secretsManager
>   type: kubernetes.io/dockerconfigjson
>   data:
>     - key: /development/mma/dockerhub
>       name: .dockerconfigjson
> ```
> 
> Where the value in backend would be
> 
> ```json
> {"auths":{"https://index.docker.io/v1/":{"auth":"bXljcmVkZW50aWFsczp2ZXJ5LW5pY2UtcGFzc3dvcmQ="}}}
> ```
> 
> Similarly could be done for tls?
> 
> ```yaml
> apiVersion: kubernetes-client.io/v1
> kind: ExternalSecret
> metadata:
>   name: my-tls
> secretDescriptor:
>   backendType: secretsManager
>   type: …
```
=> feat: allow setting type in external secret to support other than Opaque secrets

charts/kubernetes-external-secrets/Chart.yaml, charts/kubernetes-external-secrets/README.md, charts/kubernetes-external-secrets/templates/rbac.yaml, charts/kubernetes-external-secrets/templates/serviceaccount.yaml, charts/kubernetes-external-secrets/values.yaml
As stated in this PR https://github.com/helm/helm/pull/6095, the stable repository is going to be removed and they suggest an alternative way to use Helm Hub https://github.com/helm/hub. This PR updates charts base on the original PR to helm/charts repo https://github.com/helm/charts/pull/15465. Then the charts will be hosted in our repo and will make a PR to Helm Hub to add kubernetes-external-secrets helm charts
=> chore(charts): update charts

README.md, bin/daemon.js, charts/kubernetes-external-secrets/README.md, charts/kubernetes-external-secrets/values.yaml, config/environment.js, lib/daemon.js, lib/metrics-server.js, lib/metrics-server.test.js, lib/metrics.js, lib/metrics.test.js, lib/poller.js, lib/poller.test.js, package-lock.json, package.json
**What this PR does / why we need it**:
This PR Introduces a HTTP Server component that serves Prometheus metrics. We want metrics for this application to gain insights into the app and its integration with 3rd party APIs:
* do we successfully sync external secrets?
* if not what secrets, namespaces or backends are affected
This PR adds the `sync_calls` metric with labels `name|namespace|backend|status` that provide visibility for the above criteria.
=> feat: basic metrics

README.md, config/aws-config.js, config/index.js, examples/secretsmanager-example.yaml, examples/ssm-example.yaml, lib/backends/kv-backend.js, lib/backends/kv-backend.test.js, lib/backends/secrets-manager-backend.js, lib/backends/secrets-manager-backend.test.js, lib/backends/system-manager-backend.js, lib/backends/system-manager-backend.test.js, lib/poller.js, lib/poller.test.js, package.json
This PR solves #143 
It adds an option to specify a `roleArn` on a `ExternalSecret` CRD. The app will assume a role before retrieving the secret.
I tested it using `localstack` and AWS.
=> feat: add option to assume role

charts/kubernetes-external-secrets/templates/deployment.yaml, charts/kubernetes-external-secrets/templates/serviceaccount.yaml, charts/kubernetes-external-secrets/values.yaml
EKS supports specifying an IAM Role to a service account. (see #161 and https://docs.aws.amazon.com/en_pv/eks/latest/userguide/iam-roles-for-service-accounts.html)
Currently we have to create a seperate service account and link it to the deployment.
This PR adds support to add this annotation directly using the chart.
Should fix #170
=> Add support for serviceaccount annotations

bin/daemon.js, charts/kubernetes-external-secrets/templates/rbac.yaml, custom-resource-manifest.json, external-secrets.yml, lib/daemon.js, lib/daemon.test.js, lib/poller-factory.js, lib/poller.js, lib/poller.test.js
Currently kubernetes-external-secrets does excessive polling of all external secrets and doesn't respect the polling intervall. Everytime the watch stream disconnects (happens somewhat regularly) all the secrets are regenerated. In our relatively small dev cluster this generates 22 million events to each of KMS, SM and GuardDuty which generates unnecessary billing, and a general waste of compute cycles for the sake of nothing.
This PR uses the status subresource to track generation of external secret, and the last sync time.
Will use these values to determine how to queue up the next poll, either instant or time remaining for next poll intervall to pass. This helps for setting long poll intervals as currently setting something like 24h and having the pod moved or watch stream disconnected …
=> feat: add status subresource with last sync and generation tracking

lib/backends/kv-backend.js, lib/backends/kv-backend.test.js, lib/daemon.js, lib/daemon.test.js, lib/poller.js, lib/poller.test.js
Improve log messages to be abit more consistent.
Decreased log level for some to reduce spam (eg addPoller will log on debug level as start will log similar info right after)
=> chore: update log messages to use the same name format: namespace/external-secret-name

README.md, bin/daemon.js, charts/kubernetes-external-secrets/README.md, config/environment.js, lib/poller-factory.js, lib/poller.js, lib/poller.test.js
This PR fixes #174:
* (bug) sync should work when namespace annotation is present, and no roleArn is provided
* (feature) make the role-permission annotation key configurable
These issues are addressed in two separate commits.
=> fix: iam role

.travis.yml, Dockerfile, README.md, lib/backends/kv-backend.js, lib/backends/kv-backend.test.js, package.json
Adds `dataFrom` as discussed here https://github.com/godaddy/kubernetes-external-secrets/issues/94#issuecomment-505290048
alternative to #189 and includes fix for #184
---------
Allows this:
```yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
name: postgres-credentials
secretDescriptor:
backendType: secretsManager
dataFrom:
- /development/postgres/credentials
- /development/api/credentials
data:
- key: /development/auth/secret
name: authSecret
```
=> feat: add support for dataFrom

lib/backends/secrets-manager-backend.js, lib/backends/secrets-manager-backend.test.js
Should fix https://github.com/godaddy/kubernetes-external-secrets/issues/149 issue
=> Retrieve binary secrets from AWS Secrets Manager

README.md, charts/kubernetes-external-secrets/templates/deployment.yaml, charts/kubernetes-external-secrets/templates/rbac.yaml, charts/kubernetes-external-secrets/values.yaml, config/environment.js, config/index.js, examples/hello-service-external-secret-vault.yml, external-secrets.yml, lib/backends/vault-backend.js, lib/backends/vault-backend.test.js, package-lock.json, package.json
Hello all!
I've been building on @bboerst 's work from [his fork](https://github.com/tunein/kubernetes-external-secrets/tree/vault-backend) to add support for Hashicorp Vault as a backend for external-secrets. 🎉 
I've currently got this working through the bundled Helm Chart, which I've had to tweak a little to add the necessary bits and pieces.
I've also added a first draft of documentation, please let me know what you think / what could be improved!
Fixes #62
=> Support for Hashicorp Vault

charts/kubernetes-external-secrets/Chart.yaml, charts/kubernetes-external-secrets/templates/deployment.yaml, charts/kubernetes-external-secrets/values.yaml
Hello 👋 
I just realised we need to support mounting a CA file as a secret in this pod to communicate with Vault, which is best done through secrets.
This PR therefore copies the `envVarsFromSecret` construct, but for files.
I also bumped the chart version, but I'm not sure that's the correct way of doing things - please let me know if I need to do it differently!
- Florent
=> Support mounting existing secrets as files

lib/backends/vault-backend.js, lib/backends/vault-backend.test.js
Hello, it's me again 👋 
Due to changes in https://github.com/godaddy/kubernetes-external-secrets/pull/206,
we now need to stringify the response from the backend which currently comes as
an object rather than a JSON string.
Fixes issue such as:
```
{"level":30,"time":1573653228258,"pid":19,"hostname":"external-secrets-8zq4bq","msg":"running poll on the secret example/example","v":1}
{"level":40,"time":1573653228468,"pid":19,"hostname":"external-secrets-8zq4bq","msg":"Failed to JSON.parse value for 'secrets/data/example/credentials', please verify that your secret value is correctly formatted as JSON. To use plain text secret remove the 'property: apiToken'","v":1}
```
=> Vault: stringify JSON response for compatibility with KV backend

.travis.yml, config/aws-config.js, config/index.js, e2e/Dockerfile, e2e/README.md, e2e/kind.yaml, e2e/localstack.deployment.yaml, e2e/run-e2e-suite.sh, e2e/tests/crd.test.js, e2e/tests/framework.js, e2e/tests/secrets-manager.test.js, e2e/tests/setup.test.js, e2e/tests/ssm.test.js, package.json
Hey!
I'd like to add e2e tests to the repository in order to test the full path including helm chart configuration, AWS/Localstack integration and the good path (create ES, read data from SSM, wait for secret to appear). This is a first iteration, we can add more tests later on.
I also added validation to the `custom-resource-manifest.json` (using the new `.spec` field).
Unfortunately, we can't test the STS/assume-role integration - local stack does not seem to support it.
=> Feat: e2e tests

charts/kubernetes-external-secrets/README.md, charts/kubernetes-external-secrets/templates/deployment.yaml, charts/kubernetes-external-secrets/values.yaml
This feature will allow users to specify additional labels to the pods. This is very useful if you for example would like to group components that interact with a specific provider by label. 
Most likely the commit #ed5b199 is not needed. I allow edits from maintainers, so feel free to delete it's not needed, or I can do it myself.
=> Add podLabels value in chart

lib/backends/vault-backend.test.js
Following-up from #214 : better tests for Vault!
This tests the actual `vaultBackend.getSecretManifestData` method rather than only the inner `_get` method.
Also added some short-circuits that will fail early if required parameters are missing from the ExternalSecret definition.
=> Vault: add better tests, handle missing values

README.md
It is not uncommon for Vault backends to be using a cert issues by a self-signed CA. This
documents configuration changes required to use with such a backend.
=> docs: document Vault backend with self-signed CA

lib/backends/kv-backend.js, lib/backends/kv-backend.test.js
In some cases when AWS Secret Manage secret has a type `Binary` the value can be corrupted during uploading to Kubernetes.
`.SecretBinary` returns Buffer and it should not be converted.
Should fix https://github.com/godaddy/kubernetes-external-secrets/issues/235
Could you please review this @Flydiverny  @silasbw ?
=> Do not skew binary data

README.md, bin/daemon.js, config/environment.js, e2e/tests/secrets-manager.test.js, e2e/tests/ssm.test.js, lib/poller-factory.js, lib/poller.js, lib/poller.test.js
See issue #178. 
This patch is tested. It runs smoothly on two clusters since more than 4 weeks.
=> Enforcing naming conventions for AWS Secrets Manager (and HashiCorp Vault) entries

charts/kubernetes-external-secrets/templates/deployment.yaml, charts/kubernetes-external-secrets/values.yaml
Before this change, if you tried providing a ServiceAccount annotation
you will get the following error from Helm:
`coalesce.go:199: warning: destination for annotations is a table. Ignoring non-table value <nil>`
This fixes the default value so this issue doesn't happen.
There is also another fix for the annotations in the deployment so that it's more consistent with other areas. Without this, we generate an empty annotations section in the deployment when no podAnnotations are provided.
=> Fix annotation bugs

README.md
Clarify that `kubernetes-external-secrets` inherits the IAM role of the node it's running on when situated in AWS, whether its within EKS or otherwise.
Also: thank you for sharing this project, is awesome! :pray:
=> docs: Clarify IAM role usage.

crd.yaml
=> fix: remove required top level key from vault backend validation

.dockerignore, Dockerfile
Hello! I changed a few things as follows.
- Add .git in dockerignore so that the image size potentially will be decreased.
- 1 critical and 2 high security issues have been reported for Node.js and 12.15 addressed them.
- npm no longer has to be updated as the base image contains a newer version
- Remove `RUN mkdir` in Dockerfile as WORKDIR does what it does
- other simplyfing Dockerfile format
```
$ docker images
REPOSITORY              TAG              IMAGE ID          CREATED           SIZE
before                  latest           742f1e7b5381      4 seconds ago     195MB
after                   latest           0a20262f7686      35 seconds ago    177MB
```
=> Add git for dockerignore and fix CVE critical issues on nodejs

lib/poller.js, lib/poller.test.js
Vault error messages seem to have newlines and tabs which don't look great in k8s status message. This PR cleans up the status string before sending to k8s.
Before:
After:
=> Remove newlines, spaces, and tabs from status string

lib/backends/kv-backend.js, lib/backends/kv-backend.test.js
When using an external secret like below where the secret value was formated like json you might expect to get the JSON value in the secret but instead you got "[object  Object]"
```yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
name: secretsmanager-test
spec:
backendType: secretsManager
dataFrom:
- /development/mma/dockerhub
```
Secret value:
```json
{
"auths": {
"https://index.docker.io/v1/": {
"auth": "bXktc2VjcmV0LWNyZWRlbnRpYWw6bm90LW15LXBhc3N3b3JkCg=="
}
}
}
```
Gave a secret like
```yaml
apiVersion: v1
kind: Secret
metadata:
name: secretmanager-test
data:
auths: W29iamVjdCBPYmplY3Rd
type: Opaque
```
`W29iamVjdCBPYmplY3Rd` -> `[object Object]`
After this change:
`eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsiYXV0aCI6ImJYa3RjMlZqY21WMExXTnlaV1JsYm5ScFlXdzZibTkwT …
=> fix: stringify json object based secrets

README.md, crd.yaml, lib/backends/azure-keyvault-backend.js
Hi!
We had an issue with fetching certificates from the Azure KeyVaults.
Because the certificate were binary files, the Azure KeyVault would base64 encode it, however the @azure/keyvault-secrets library gives no notice or way to detect that the secret is base64 encoded.
Then kubernetes-external-secrets would base64 encode it again, so the binary files were base64 encoded twice, which meant that we had to alter our application to base64 decode the certificates before we could use them.
Here we add a new `keyOptions` field `isBinary` so that you can explicitly specify that the Azure KeyVault secret is a binary and that no base64 encoding should happen.
Notice that the `isBinary` field does not work together with the `property` field, as the `property` field does JSON-decode and that would …
=> fix(azure-registry): handle binary files

README.md, lib/metrics-server.test.js, lib/metrics.js
It is a bit difficult to alert on sync_calls since they trigger into an error state and may stay there.
This adds the gauge last_state.  With last_state, people can easily alert on a value < 0 to indicate failure.
=> Add last_state metric

config/aws-config.js
The default STS configuration uses the legacy global endpoint, which does not work from private VPCs accessing STS via VPC Endpoints.  This change adds the `region` and `stsRegionalEndpoints` values to the `stsConfig` object used to construct the STS client.  It defaults to "regional" as the value of `stsRegionalEndpoints` but honors the `AWS_STS_ENDPOINT_TYPE` environment variable for users who prefer/require the use of "legacy" endpoints.
=> Enable use of AWS STS regional endpoints

README.md
This block for azure binary files is not under the azure headline. It was bothering me
=> Update readme. Azure docs out of order

Dockerfile, charts/kubernetes-external-secrets/README.md, charts/kubernetes-external-secrets/values.yaml
**Background**
We run our EKS clusters with locked-down `PodSecurityPolicy` by default; that is we drop all privileges and change the default EKS policy to one that is essentially unprivileged.
`kubernetes-external-secrets` does not appear to require any particular privileges that are from the set.
This makes two changes to allow the chart/image to work out of the box without configuration on the user side.
1. changes the `Dockerfile` to indicate the user as `uid` 1000 rather than `node`, which is required to indicate K8S that it's not running as root (when running under Docker, at least) - [consistent with the base node images](https://github.com/nodejs/docker-node/blob/master/12/alpine3.11/Dockerfile#L6)
Minimal workaround on `3.2.0` without the change in this PR is a `values.yaml` …
=> Improve out-of-the-box compatibility with clusters running PodSecurityPolicy

README.md, charts/kubernetes-external-secrets/values.yaml, examples/hello-service-external-secret-gcp.yml
See https://github.com/godaddy/kubernetes-external-secrets/issues/370
Update documentation and default values.yaml for Google Secret Manager.
=> Issue #370 Update values.yaml and README for Google Secret Manager

config/index.js
In HA mode, Vault may return 307 redirect responses. This sets `followAllRedirects: true` so that VaultClient follows these 307 redirects for non-GET requests (kubernetesLogin, refreshTokenSelf).
See: https://github.com/kr1sp1n/node-vault/issues/23
=> fix(vault): follow all redirects to support vault HA

e2e/run-e2e-suite.sh
For some reason, in cluster started by `kind`, `core-dns` doesn't start
```
plugin/loop: Loop (127.0.0.1:55953 -> :1053) detected for zone ".", see https://coredns.io/plugins/loop#troubleshooting.
```
which messes with internal cluster communication between services and makes e2e tests to fails due to timeout 
```
Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/app/e2e/tests/secrets-man
ager.test.js)                                                                                                                                                         
at listOnTimeout (internal/timers.js:549:17) …
```
=> feat: bump kindest/node version

lib/poller.js, lib/poller.test.js
While documentation says that `permitted-key-name` can be provided as regular expression
```
kind: Namespace
metadata:
name: core-namespace
annotations:
externalsecrets.kubernetes-client.io/permitted-key-name: "/dev/cluster1/core-namespace/.*"
```
it would be nice (clearer ?) if it can support _list_ of regular expressions
```
kind: Namespace
metadata:
name: core-namespace
annotations:
externalsecrets.kubernetes-client.io/permitted-key-name:
- "/dev/cluster1/core-namespace/.*"
- "/common/.*"
```
=> feat: allow permitted-key-name to be provided as list

config/aws-config.js
This PR adds support for AWS IAM authentication using web identity token file. Primary use case is Fargate IRSA.
Summary:
* when env variable AWS_WEB_IDENTITY_TOKEN_FILE is present the contoller will now use assumeRoleWithWebIdentity
* chart has to be deployed with --set securityContext.fsGroup=65534 in order to access web identity token
Closes #254
=> add support for assumeRoleWithWebIdentity when used on AWS Fargate IRSA

charts/kubernetes-external-secrets/crds/kubernetes-client.io_externalsecrets_crd.yaml, examples/vault-kv1.yaml, lib/backends/vault-backend.js, lib/backends/vault-backend.test.js, package-lock.json, package.json
Closes #299
Fixes #248 
Closes #425 
Closes #349 
Adds a `kvVersion` flag to vault backend:
```yaml
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
name: database-credentials-from-kv1
spec:
backendType: vault
vaultMountPoint: my-kubernetes-vault-mount-point
vaultRole: my-vault-role
kvVersion: 1 # <---------- K/V version to be able to parse api response correctly
data:
- name: username
key: kv/database
property: db-username
- name: password
key: kv/database
property: db-password
```
=> feat: add support for using either Vault k/v 1 or k/v 2

README.md, lib/backends/kv-backend.test.js, lib/backends/secrets-manager-backend.js, lib/backends/secrets-manager-backend.test.js, lib/poller.js
This PR resolves https://github.com/godaddy/kubernetes-external-secrets/issues/435.
Added supporting versionId of AWS Secrets Manager.
=> AWS Secrets Manager: Support versionId

charts/kubernetes-external-secrets/values.yaml, config/environment.js, config/index.js
Switch from the following log messages:
```
{"level":30,"time":1594499119283,"pid":18,"hostname":"kubernetes-external-secrets-56d5969cd6-gdkb4","msg":"starting poller for asdf/database-credentials"}
```
to 
```
{"level":"info","time":1594499119283,"pid":18,"hostname":"kubernetes-external-secrets-56d5969cd6-gdkb4","msg":"starting poller for asdf/database-credentials"}
```
Many log aggregation tools parse the logs for human readable log levels like "warning" or "error". This makes it easier to send alerts based on those logs, etc.
=> Switch to human-readable log levels

charts/kubernetes-external-secrets/values.yaml, config/environment.js, config/index.js, package-lock.json, package.json
`useHumanReadableLogLevels` is deprecated and will be removed in `pino@7`
=> refactor(logger): update to support pino@7

bin/daemon.js, config/environment.js, lib/poller-factory.js, lib/poller.js, lib/poller.test.js
Namespace annotations are amazing, but there is no way to make them mandatory. Added an env var that when set, makes those annotations mandatory.
=> added the option to enforce namespace annotations

config/aws-config.js
Fixes #442, see https://github.com/godaddy/kubernetes-external-secrets/issues/442#issuecomment-664084389 for more details
Effectively reverts changes introduced in #416 and #417
=> fix: reverts assumeRole to use pod role instead of web identity

README.md
This pr adds a tiny section on how to create non-opaque secrets (using template). Currently you have to search through issues in order to find this information (for example #359)
=> Added section for non-opaque secrets creation

README.md
The `SecretDescriptor` property was still used in an example, even though `spec` has been the norm for a while now. This helps correct behavior for people copy-pasting code.
=> doc: use new API standard in example

lib/backends/system-manager-backend.js, lib/backends/system-manager-backend.test.js
Related to https://github.com/godaddy/kubernetes-external-secrets/issues/265
When a requested key does not exist in AWS SSM the Externalsecret status currently reads `ERROR, null` because the AWS error has 'null' as its message. This change would add a meaningful error message.
The issue mentioned above suggests to skip the missing key. I think that would mask the underlying problem though. Let me know what you prefer.
=> Provide a meaningful error message when an SSM parameter is missing

README.md, charts/kubernetes-external-secrets/crds/kubernetes-client.io_externalsecrets_crd.yaml, config/environment.js, config/index.js, lib/backends/vault-backend.js, lib/backends/vault-backend.test.js
This PR enables global default `Vault Role` and `Vault Mount Point` setting for k8s authentication to Hashicorp Vault. 
**Reason:**
When a user tries to deploy an app to multiple different cluster which uses the same vault. The `External Secret` yaml file has differences since, `vaultRole` and `vaultMountPoint` could be different for different clusters. This leads to multiple `External Secret` yaml file. One for each cluster. Whereas this could be specified during deployment of External Secret helm chart. 
Since, a cluster will most probably will have one `vaultMountPoint`. It is better to have a way to deploy it at the config level. Leaving the user not to worry about role and mount point and focus on the values retrieved from the vault. Since, it is a default value. This will be …
=> feat: Cluster level default settings for Hashicorp Vault

CODE_OF_CONDUCT.md
I noticed that this project was only inheriting the code of conduct from https://github.com/godaddy/.github/blob/master/CODE_OF_CONDUCT.md -- adding it directly into the repo here to make it more easily discoverable for new contributors.
=> Adopt the Contributor Covenant Code of Conduct

.github/workflows/workflow.yml, .gitignore, e2e/Dockerfile, e2e/kind.yaml, e2e/run-e2e-suite.sh
E2E test broke due to kind being bumped to 0.9.0 (not sure what and where the binary is provided? in the ubuntu CI image?)
api version for kind needed an update.
=> fix: e2e tests to work with kind 0.9.0 + bump k8s version used

README.md
Having the default chart values being set with the `-f` flag is kinda confusing and redundant. Don't you think? 🤔 
Cheers!
=> chore(docs): Remove redundant -f in helm template

config/index.js, lib/backends/vault-backend.js, lib/backends/vault-backend.test.js
Fixes https://github.com/godaddy/kubernetes-external-secrets/issues/487
When you have a single k8s cluster with multiple namespaces and each `ExternalSecret` is defined with a very limited scoped `vaultRole` (limiting the vault data that role can read) the existing token caching causes issues.
This change caches each `vaultClient` against the `vaultRole` it's authenticated against and can therefore KES can read all the secrets it is meant to regardless of how many `vaultRoles` are defined across your ExternalSecrets
=> Cache Vault clients/tokens on a per-role&mountpoint basis.

README.md, e2e/tests/secrets-manager.test.js, e2e/tests/ssm.test.js, examples/secretsmanager-example.yaml, examples/ssm-example.yaml, lib/backends/kv-backend.test.js, lib/backends/secrets-manager-backend.js, lib/backends/secrets-manager-backend.test.js, lib/backends/system-manager-backend.js, lib/backends/system-manager-backend.test.js
This PR adds multi-region support for ssm and sm #354
I feel like we should (somehow) cache & reuse the ssm/sm `client` object so we don't assume a role in each `_get` call. E.g. by using the hash of the `ExternalSecret` or `${namespace}/${name}/${metadata.generation}` as cache key for the client object.
=> feat(aws): add region support to ssm and sm

charts/kubernetes-external-secrets/README.md, charts/kubernetes-external-secrets/templates/deployment.yaml, charts/kubernetes-external-secrets/values.yaml
This is a common feature of many Helm charts, and is important for
ensuring that the external-secrets pod is scheduled with a higher
priority than other workloads.
=> Add the ability to set the priorityClassName

README.md, lib/metrics-server.test.js, lib/metrics.js, lib/metrics.test.js
Hello,
This PR refactors the metrics' names according to  [Prometheus metric names best practices](https://prometheus.io/docs/practices/naming/#metric-names).
No breaking changes at the moment since I added new metrics and added deprecation notes on the old ones.
Related to: #489
=> Better naming for Prometheus metrics

package-lock.json
As per Snyk report (https://snyk.io/test/npm/lodash/4.17.19), bumping lodash version to latest one, as 4.17.19 contains high severity Prototype Pollution
=> Bumping lodash from 4.17.19 to 4.17.20

package-lock.json
Bumping @grpc/grpc-js to 1.1.8 to address  Prototype Pollution issue: https://app.snyk.io/vuln/SNYK-JS-GRPCGRPCJS-1038818
=> Bumping @grpc/grpc-js to 1.1.8

README.md
Hey there!
Adding a more explicit header about moving the project to the new GitHub organization, since it could have generated problems we weren't aware of, like the Helm issue mentioned in the issue.
=> Add information on moving the repository from GoDaddy to external-secrets

charts/kubernetes-external-secrets/README.md
I noticed the installation instructions are slightly out-of-date in the Helm Chart's README. I updated any GoDaddy references that linked to the Github repository. Issue #554 is tracking some of these issues, so I will link it here for visibility.
Thanks for this project, it's great!
=> Fix some old repo name references in Helm chart README

config/index.js
The logger is generating a invalid json with duplicate keys in some circustances.
Use the nestedKey of the pino logger to avoid this issue, and log the objects under a "payload" key.
Example:
```
{
"level": 50,
"time": 1591347107037,
"pid": 19,
"payload": {
"hostname": "kubernetes-external-secrets-6799c84569-kfjcj",
"message": "Access to KMS is not allowed",
"code": "AccessDeniedException",
"time": "2020-06-05T08:51:47.036Z",
"requestId": "1894b6c9-b698-4657-a3cb-ecd8f044afee",
"statusCode": 400,
"retryable": false,
"retryDelay": 77.07928574264942,
"stack": "AccessDeniedException: Access to KMS is not allowed\n    at Request.extractError (/app/node_modules/aws-sdk/lib/protocol/json.js:51:27)\n    at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:106:20)\n …
```
=> Configure nestedKey in logger to avoid invalid json

charts/kubernetes-external-secrets/values.yaml
closes #522
Readme and value usage already expects `imagePullSecrets` to be root level indentation.
=> fix(values): imagePullSecrets was wrongly indented under image

README.md, charts/kubernetes-external-secrets/crds/kubernetes-client.io_externalsecrets_crd.yaml, examples/hello-service-external-secret-gcp.yml, examples/hello-service-external-secret-vault.yml, lib/backends/azure-keyvault-backend.js, lib/backends/gcp-secrets-manager-backend.js, lib/backends/kv-backend.js, lib/backends/kv-backend.test.js
- Add support for `isBinary` in `KVBackend` + tests
- Remove specific implementation of `isBinary` from Azure Key Vault & GCP Secrets Manager backends
- Update description for `isBinary` field in the CRD to remove Azure-specific details
- Update docs
- Support for binary secrets was missing in Hashicorp Vault backend
- #311 (Azure) and #353 (GCP) added support for `isBinary` for specific backends, both using the same approach
- However, that could not be replicated for Hashicorp Vault because there is no concept of "text strings" secrets in Vault - all secrets hold key-value pairs. Since `property` is not available in `VaultBackend`, you cannot handle binary secrets there either.
- After fixing #460 (Azure) and #373 (GCP), all backends return a response of same type(s) and structure. So …
=> feat: add general support for isBinary for all backends

config/aws-config.js, package-lock.json, package.json
Hi All,
I aws trying to debug why I could not connect to AWS endpoints with an environment that does not use the Internet (private environment). I figured out that proxy settings need to be passed explicitly to AWS SDK: https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/node-configuring-proxies.html
I am not a NodeJS developer, so feel free to help me out if you think this code is not good enough.
Best,
Mark.
=> Pass proxy to AWS SDK

.github/workflows/workflow.yml, README.md, bin/daemon.js, charts/kubernetes-external-secrets/README.md, charts/kubernetes-external-secrets/values.yaml, config/environment.js, e2e/README.md, lib/external-secret.js, lib/external-secret.test.js
Hello,
This PR is 1 of 2 PRs to address support for multitenancy.
At the moment KES is not scoped, which means it works cluster-wide and there is no way to scope its access. Thus, cannot deploy 2 KES in the same cluster will different access.
So this PR allows allow to watch `externalsecrets` in specified namespaces which fix a couple of issues:
1. It allows to deploy more than 1 operator per cluster, so each tenant can deploy their own KES and optimize it according to thier workload.
2. Covers more use cases for security separation since using namespace annotation doesn't fit all use cases because in some workloads the tenant (e.g. devs) are able to create and edit namespaces.
3. Limit the access of KES service account (which used for Vault role for example) where it has gigantic access …
=> feat(multitenancy): Allow to watch ExternalSecrets in specific namespaces

.github/workflows/stale.yml
This PR adds a workflow which runs daily to:
* mark issues without activity as `stale` after 90d
* close stale issues after 30d with no activity
See [actions/stale](https://github.com/actions/stale).
@Flydiverny could you plase take a look at this :heart:  ?
=> add stale workflow to auto-close issues

README.md, charts/kubernetes-external-secrets/values.yaml, config/aws-config.js
Allow custom endpoints for aws services
Useful if you need to use the FIPS endpoints ->  https://docs.aws.amazon.com/general/latest/gr/asm.html
Or less likely use case if you need to override to use VPC endpoints when using custom DNS -> https://docs.aws.amazon.com/secretsmanager/latest/userguide/vpc-endpoint-overview.html
kubernetes-external-secrets is amazing and FIPS support is required for running it in fedRAMP compliant environments.
Signed-off-by: S.Cavallo <smcavallo@hotmail.com>
=> feat(aws): allow custom endpoints for aws services

README.md, charts/kubernetes-external-secrets/crds/kubernetes-client.io_externalsecrets_crd.yaml, config/aws-config.js, e2e/tests/crd.test.js, e2e/tests/ssm.test.js, examples/ssm-example.yaml, lib/backends/kv-backend.js, lib/backends/system-manager-backend.js, package.json
This MR is a replacement of my original approach (https://github.com/external-secrets/kubernetes-external-secrets/pull/238 )
I have refactored the code to do have as little changes as possible but still supporting the possibility of fetching secrets from a path instead of a key.
Also added support to fetch paths recursively if needed but the default is 0.
=> feat(aws-ssm): Support parameters by path

lib/backends/kv-backend.js
Currently, with the Vault backend, only top-level properties can be used for formatting Secrets: [https://github.com/external-secrets/kubernetes-external-secrets/blob/master/lib/backends/kv-backend.js#L47](https://github.com/external-secrets/kubernetes-external-secrets/blob/master/lib/backends/kv-backend.js#L47)
We would like to be able to support nested property lookups for more complex Vault JSON secrets.
I added a simple lodash implementation to check whether the nested property exists, then fetch the value if it does.
=> feat: adds lodash get function for nested keys lookup

README.md
Believe this should be `systemManager` not `secretsManager`
=> chore(docs): fix backendType for AWS SSM Parameter Store example

charts/kubernetes-external-secrets/templates/rbac.yaml
`.Capabilities.KubeVersion.GitVersion` has `-eks-<hash>` in EKS. e.g. `v1.19.6-eks-49a6c0`  
This semantic version was judged Prerelease version by semver function.
Prerelease version un comparable for release version.
As a workaround ref https://helm.sh/docs/chart_template_guide/function_list/#working-with-prerelease-versions
=> Add patch version semverCompare

lib/backends/secrets-manager-backend.js
This pull requests adds the following enhancement:
- An accurate info log message when the AWS region is not specified in the ExternalSecret manifest but uses the `AWS_REGION` env var as explained in https://github.com/external-secrets/kubernetes-external-secrets/issues/635
The idea is not to mislead the users by throwing an undefined in an info log message.
It is very small I know, but this simple addition can help not having any doubt about if external-secret is doing properly the task or not.
=> Enhance info log message about region for AWS SM backend

lib/backends/system-manager-backend.js
- The secret manager was supported in the PR below, but it was supported because the system manager is not supported.
- https://github.com/external-secrets/kubernetes-external-secrets/pull/641
=> Enhance info log message about region for AWS System Manager backend

Dockerfile
Hi,
this PR updates the Docker base image to the latest node 12 LTS minor release available on Docker Hub.
12.x is in maintenance mode until 2022-04-30. However, it should be considered to switch to the active LTS release 14.x which will be in maintenance mode until 2023-04-30. I am not sure how many breaking changes were introduced by node between 12.x and 14.x.
Best
Nick
=> Update base image from 12.19.0-alpine to 12.21.0-alpine

config/index.js
=> fix!: rename time field to avoid duplicate time key in log output

lib/external-secret.js, lib/external-secret.test.js, package-lock.json, package.json
=> fix: use getObjectStream to address deprecation warning in kubernetes-client

README.md
A recent change (https://github.com/external-secrets/kubernetes-external-secrets/commit/8ff9490904a9fd6eea70562e7a5349a88cb866d4) split the GCP documentation so that the workload identity and service account key deployment instructions were no longer adjacent. This change puts the GCP docs back together.
=> docs: unsplit the GCP documentation

README.md
Hi,
this PR adds a section with related projects to the README. The section currently only lists [khcheck-external-secrets](https://github.com/Nick-Triller/khcheck-external-secrets).
=> Add related project "khcheck-external-secrets" to README

package-lock.json
=> fix: update transitive netmask dependency to resolve CVE-2021-28918

charts/kubernetes-external-secrets/crds/kubernetes-client.io_externalsecrets_crd.yaml, e2e/Dockerfile, e2e/README.md, e2e/run-e2e-suite.sh, e2e/tests/crd.test.js, e2e/tests/secrets-manager.test.js
Cherry picks from #681 
- fix invalid CRD test
- add test for template.type
=> fix!: require .spec field in CRD validation

charts/kubernetes-external-secrets/Chart.yaml
This addresses #697. Lemme know if I overlooked something.
=> fix: bump Helm chart API version

README.md, charts/kubernetes-external-secrets/README.md
The helm install command is missing the name parameter, so it does not work on helm 3.2.1 at least.
=> Update README.md - Fix helm install command

README.md, charts/kubernetes-external-secrets/crds/kubernetes-client.io_externalsecrets_crd.yaml, config/environment.js, lib/daemon.js, lib/daemon.test.js
As discussed in PR #549 but using the `spec.controllerId` instead of the annotation as @Flydiverny suggested.
=> feat(Multitenancy): scope KES access using ExternalSecret config

.gitignore, lib/daemon.js
The check to see if a externalSecret should be managed by the running instance is not properly checking if `event.object` is present before evaluating the `spec` field.
=> Fix startup crash and ignore vscode config

README.md
Add the missing steps to grant GSA access to fetch secrets.
=> docs: grant GCP sa access to secret manager

README.md
Replaces `Hashicorp Vaule` by `Hashicorp Vault` in README.md
=> docs: fix Vault typo in readme

charts/kubernetes-external-secrets/crds/kubernetes-client.io_externalsecrets_crd.yaml
updated CRD was not keeping observedGeneration in status fields causing next poll to always be scheduled in 0ms 
Fixes #746
=> fix: add observedGeneration to CRD status fields

charts/kubernetes-external-secrets/crds/kubernetes-client.io_externalsecrets_crd.yaml
Closes #753
The empty properties here also produces invalid json schema when used with https://github.com/yannh/kubeconform
=> CRD property types

lib/external-secret.js
Related: #763 
If there are no data events, the reset timer is never started.  If the connection to the kube api server is lost during this time and new events come in they are never seen and the stream is never restarted.
Repro: (I used minikube with ssh access)
Install helm chart
`minikube ssh`
Drop current connection from pod to api server: e.g. `conntrack -D conntrack -s 172.17.0.6 -d 10.96.0.1`
Create a new example secret (failures to connect don't matter here)
Note that the secret is not picked up nor is the server restarted. `kubectl get externalsecrets.kubernetes-client.io`
Credit and thanks to https://github.com/external-secrets/kubernetes-external-secrets/issues/362#issuecomment-719989503 for the iptables idea.
=> Ensure that the restart timer is always started

charts/kubernetes-external-secrets/templates/rbac.yaml, lib/poller.js, lib/poller.test.js
This implements a rudimentary data check on secrets polled to only call put/post actions when the data of the secret has changed.
This is aimed at resolving #737
=> feat: Upsert secrets only when needed

README.md
Looks like it was moved out of order making GCP portion hard to follow
=> Fix order of README for clarity

README.md
Export an new environment variable with your IBM Secrets Manager service endpoint URL.
refer to : https://cloud.ibm.com/docs/secrets-manager?topic=secrets-manager-cli-plugin-secrets-manager-cli
=> chore(docs): add new env var for IBM Secret Manager plugin version 0.0.8 or later

lib/backends/ibmcloud-secrets-manager-backend.js
The result of IAM credentials type is difference from other types.  It does not contains a `secret_data` field. 
Below is an example:
```
{
"metadata": {
"collection_type": "application/vnd.ibm.secrets-manager.secret+json",
"collection_total": 1
},
"resources": [
{
"access_groups": [
"AccessGroupId-xxxxx"
],
"api_key": "xxxxxx",
"created_by": "xxx-xxxxx",
"creation_date": "2021-07-12T04:57:49Z",
"crn": "crn:v1:bluemix:public:secrets-manager:us-east:a/xxxx:xxxxx:secret:xxxxx",
"id": "xxxxx",
"labels": [
],
"last_update_date": "2021-07-12T05:58:27Z",
"name": "to-be-delete",
"reuse_api_key": false,
"secret_type": "iam_credentials",
"service_id": "ServiceId-xxxxxx",
"state": 1,
"state_description": "Active",
"ttl": 86400
}
]
}
```
=> fix(IBM): correctly extract secret data for IBM IAM credentials type secrets

lib/poller.js, lib/poller.test.js
The permission checking code is currently ignoring the `path` attributes when evaluating. This results in permission checks for secrets defined like this:
```
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
name: test
spec:
backendType: systemManager
data:
- path: dev/team-a/secret
```
with the error message `ERROR, not allowed to fetch secret: test/test: key name undefined does not match naming convention ^dev/team-a/.*`.
This PR adds handling of the `path` attribute in the permissions check.
=> Fixes naming convention permission check for data items with path attribute.

charts/kubernetes-external-secrets/README.md, charts/kubernetes-external-secrets/templates/deployment.yaml, charts/kubernetes-external-secrets/values.yaml
Have a use case where we want to add labels to the deployments, but were currently unable to do so with the charts.  Adding this optional value
=> Add optional deployment labels value to charts

lib/poller.js, lib/poller.test.js
This change fixes the false positive in the permission checking code when the `path` attribute is used. Without the fix, the added test fails, as the as the code always tries to check the `key` attribute, even when only `path` is provided. It ends up coercing the `undefined` value to a sting and testing that.
=> Fixes naming convention permission check for data items with path attribute only.

charts/kubernetes-external-secrets/values.yaml, e2e/README.md, e2e/run-e2e-suite.sh
Not sure why AWS_DEFAULT_REGION was added in the first place, but it seems misleading to have. Its not provided in the docs everywhere and the AWS SDK for JS uses `AWS_REGION` so the `AWS_DEFAULT_REGION` should not be used, if one uses the aws cli it does seem to prefer `AWS_DEFAULT_REGION` though in some cases 😄
=> fix: remove AWS_DEFAULT_REGION

README.md, charts/kubernetes-external-secrets/crds/kubernetes-client.io_externalsecrets_crd.yaml, examples/ibmcloud-secrets-manager.yaml, lib/backends/ibmcloud-secrets-manager-backend.js, lib/backends/ibmcloud-secrets-manager-backend.test.js
This PR adds support for using names, instead of IDs, as the `key`s in `ExternalSecret`s with IBM Cloud Secrets Manager.
With the current backend implementation, the `key` on each `data` item is assumed to be an ID, which is assigned to each secret by Secrets Manager on creation. Secrets Manager's API and CLI are totally oriented around these IDs, which are generally not meaningful or useful to users. Users assign a name, not an ID, to secrets, and they should be able to reference them by that name. Fortunately, Secrets Manager's API does allow you to search for a secret by name and get its ID, so clients can use that to support referencing secrets by name.
If I am defining `ExternalSecret`s in YAML and committing it to Git, I definitely want to put the names of the secrets in those …
=> feat(ibm): Support looking up secrets in IBM Cloud Secret Manager by name

README.md, charts/kubernetes-external-secrets/crds/kubernetes-client.io_externalsecrets_crd.yaml, lib/backends/kv-backend.js, lib/backends/kv-backend.test.js
This PR resolves this request: https://github.com/external-secrets/kubernetes-external-secrets/issues/823.
**Use case**:
While following GitOps practice, we try to keep our deployments immutable and when it comes to secrets management - we always specify the `versionId` of any secret we use in Git.
In the same time, we do really like existent `dataFrom` feature, which releases us from going thought each secret's property in order to get it populated in the Kubernetes secret.
However, with the existent implementation, `dataFrom` retrieves only the latest secret version, which breaks our GitOps & deployments immutability approach.
`dataFromWithOptions` allows getting all the values in bulk (as it is now with simple `dataFrom` option) but gives the possibility to specify the secret version …
=> feat(secretsManager): ✨  Introduce dataFromWithOptions

bin/daemon.js
Small enhancement for #826: export default `nodejs_*` metrics. They can be displayed with the [nodejs app dashboard](https://grafana.com/grafana/dashboards/11159).
=> feat: add runtime metrics

README.md
Now that it's been a while, I thought it would be better if we didn't have the 'Repository moved to external-secrets' text as the first thing which someone read :)
=> Add a more appropriate' history' heading

charts/kubernetes-external-secrets/values.yaml, config/azure-config.js, lib/backends/azure-keyvault-backend.js
Support providing Azure Environment-oriented KeyVault endpoints
=> Support Azure sovereign cloud environments

README.md
Expands on the AWS SSM Parameter Store docs with examples of how to fetch a specific version of a given parameter.
Whilst this is not technically a feature offered by the package directly and instead supported by the underlying AWS SDK, it's a very useful feature worth highlighting which allows immutable, versioned controlled references to SSM instead of always fetching the latest value that can change.
=> Expand SSM Parameter Store docs to clarify use of version constraints

examples/ibmcloud-secrets-manager.yaml
Currently, the the IBM Cloud Secrets Manager example is very minimalistic. The example also states that only secrets of type username_password, arbitrary, or iam_credentials can be retrieved. Recently, all secret types can be retrieved (including certificates).
=> chore(docs): Extension of the IBM Secrets Manager example

package-lock.json
=> fix(deps): bump node-forge CVE-2022-24772 CVE-2022-24771 CVE-2022-0122
