package-lock.json
package.json

Addresses https://app.snyk.io/vuln/npm:chownr:20180731

chore(nodemon): move to devDependencies and update

---

README.md
config/index.js
examples/hello-service-external-secret.yml

NEED TO CREATE NEW DOCKER IMAGE AND SEPARATE PR TO UPDATE TAG IN DEPLOYMENT FILES.

fix(backends): fix secretsManager backend name

---

package.json

Inlcude --fix in `lint`; run linting (without --fix) during `test`.

chore(lint): adjust `lint` and `test` scripts

---

lib/backends/kv-backend.js
lib/backends/kv-backend.test.js

This mirrors `Secret` objects.

feat(data): support `.data` in the `secretDescriptor`

---

config/index.js
package-lock.json
package.json

chore(package): update kubernetes-client to version 8.1.1

---

api.md

Propose and document an API for writing secret data to volumes.
See: https://github.com/godaddy/kubernetes-external-secrets/issues/78

docs(frontends): propose a volume-based "frontend"

---

README.md
charts/kubernetes-external-secrets/templates/deployment.yaml
charts/kubernetes-external-secrets/values.yaml

per this issue I opened: https://github.com/godaddy/kubernetes-external-secrets/issues/92

Support env vars from secrets in chart

---

charts/kubernetes-external-secrets/README.md
charts/kubernetes-external-secrets/templates/NOTES.txt

add a README.md and NOTES.txt for chart to get reviews before making a PR to helm/charts repo

docs(helm): add README and NOTE.txt for chart

---

README.md
charts/kubernetes-external-secrets/README.md
charts/kubernetes-external-secrets/values.yaml

chore: remove events interval milliseconds references

---

lib/backends/abstract-backend.test.js
lib/backends/kv-backend.test.js
lib/poller.js
lib/poller.test.js

Fixing the following issue: https://github.com/godaddy/kubernetes-external-secrets/issues/114

feat(logging): specified secret names and fixed a couple typos

---

external-secrets.yml
release.sh

Also bumped the version to the latest released version manually.
Also changed Deployment apiVersion because extensions/v1beta1 is
deprecated.

Add external-secrets.yml patching to release.sh

---

external-secrets.yml

fix: add missing rbac rules to external-secrets.yml

---

charts/kubernetes-external-secrets/README.md
charts/kubernetes-external-secrets/templates/deployment.yaml
charts/kubernetes-external-secrets/values.yaml
package-lock.json
package.json

It is a second attempt to do it (first is https://github.com/godaddy/kubernetes-external-secrets/pull/176). With recent changes it is easier.
- AWS SDK version was updated
- securityContext parameter in a helm chart was added
It should fix this issue https://github.com/godaddy/kubernetes-external-secrets/issues/161 
Sorry @farshad-hobsons if you are working on it now.
@Flydiverny @silasbw could you please review it?

Integration with AWS IAM Roles for ServiceAccounts

---

package.json

This field doesn't reflect the current state of affairs and is potentially
confusing to new contributors.

chore(maintainer): remove maintainer from package.json

---

lib/backends/kv-backend.js
lib/backends/kv-backend.test.js
lib/backends/secrets-manager-backend.js
lib/backends/secrets-manager-backend.test.js
lib/backends/system-manager-backend.js
lib/backends/system-manager-backend.test.js
lib/backends/vault-backend.js
lib/backends/vault-backend.test.js

Built ontop of #204, so excuse the double diff until rebased, and lets wait for #198 anyway
@silasbw thoughts? 🙃 (ignore spec and look at kv-backends and friends)

refactor: make kv backend more generic

---

bin/daemon.js
charts/kubernetes-external-secrets/README.md
config/environment.js
lib/poller-factory.js
lib/poller.js
lib/poller.test.js

feat: allow disabling of interval polling

---

lib/poller.js
lib/poller.test.js

fix: status update conflicts should not cause crash, fixes #199

---

lib/backends/kv-backend.js
lib/backends/kv-backend.test.js
package-lock.json

Add empty keyOptions for dataFrom case.

---

package-lock.json
package.json

fix: bump pino and sub dependency flatstr, fixes #218

---

charts/kubernetes-external-secrets/templates/deployment.yaml

this one remains:
https://github.com/godaddy/kubernetes-external-secrets/blob/74f0883036710e70e9d78cdc19b02a4556da5a36/charts/kubernetes-external-secrets/templates/deployment.yaml#L56-L59

fix(chart): remove one of the duplicate securityContext

---

charts/kubernetes-external-secrets/README.md
charts/kubernetes-external-secrets/templates/deployment.yaml
charts/kubernetes-external-secrets/values.yaml

Add the ability to specify a docker conf secret to pull a custom image of external secrets

Add configurable docker credentials

---

lib/backends/gcp-secrets-manager-backend.js

feat: support isBinary for GCP

---

examples/hello-service-external-secret-gcp.yml
lib/backends/gcp-secrets-manager-backend.js
lib/backends/gcp-secrets-manager-backend.test.js

Fixes #372 
Fixes #369 
It's a breaking changes, because the content of the secret will change

Handle JSON in GCP Secrets Manager

---

e2e/tests/secrets-manager.test.js

Add e2e to test that `permitted-key-name` prevents `ExternalSecret` from accessing keys if regex doesn't match key's path
```
CRD
✓ ensure CRD is managed correctly
✓ should reject invalid ExternalSecret manifests
secretsmanager
✓ should pull existing secret from secretsmanager and create a secret with its values (2247ms)                                                                   
✓ should pull TLS secret from secretsmanager (134ms)
permitted annotation
assuming role
✓ should not pull from secretsmanager (3435ms)
enforcing naming convention
✓ should not pull from secretsmanager (3427ms)
ssm
✓ should pull existing secret from ssm and create a secret from it (130ms)
permitted annotation
✓ should not pull from ssm (3427ms)
8 passing (13s)
```
PS: `should not pull from secretsmanager` …

feat: add e2e test for naming conventions enforcement

---

package-lock.json
package.json

upgrade the Azure Identity SDK and Azure KeyVault secret SDK to support AKS pod identity for authorization.

upgrade the Azure SDK ver for azure pod identity

---

config/index.js

@keweilu would you mind creating a new release after merging this?

fix(pino): messageKey option as root constructor property

---

charts/kubernetes-external-secrets/templates/deployment.yaml
charts/kubernetes-external-secrets/templates/service.yaml

This PR applies the release namespace to the Deployment and Service.

fix(helm): apply namespace to Deployment and Service, fixes #470

---

config/index.js
lib/backends/vault-backend.js
lib/backends/vault-backend.test.js

(note this also includes PR #488 - will tidy up after that one is merged)
This fixes #484

Handle token failures

---

README.md

Adding www.lgtm.com report to README.md

Adding www.lgtm.com report to README.md

---

README.md

Fixes https://github.com/external-secrets/kubernetes-external-secrets/issues/538

Document the need to encrypt secrets in etcd

---

README.md

Given that it's been a while since the project has moved, the exclamation mark looks scary :)

Remove exclamation mark

---

charts/kubernetes-external-secrets/values.yaml

See https://github.com/external-secrets/kubernetes-external-secrets/issues/633

#633 Document replicaCount property in values.yaml

---

.github/workflows/workflow.yml

Run scans against the container image. 
related: #657, #646

feat: add container scan

---

.github/.dependabot.yml
.github/workflows/build-container.yaml
Dockerfile

- Builds docker images in CI with automatic tagging 
- builds multi arch amd64 + arm64, should we add others?  resolves #662 #551
- pushes branch and PR builds to alternative repository kes-dev

feat: automated docker image build with multi arch (amd64 + arm64)

---

package-lock.json

This is a full update of package-lock.json updating all deps within allowed dependency ranges.
Somewhat related to #657

fix: update transitive deps

---

lib/external-secret.js
lib/external-secret.test.js

fix: watch without namespace path if watching all namespaces

---

.github/workflows/build-container.yaml
.github/workflows/workflow.yml

chore: scan image built in pipeline

---

.github/workflows/build-container.yaml

Hi everyone,
This a small change to support ARM v7 so that the project can run on a Raspberry Pi.
Thanks :)

Add arm v7 as docker multi arch target

---

.github/workflows/build-container.yaml
.github/workflows/nightly.yaml

chore: add nightly job and move security scan, upload results to github security

---

bin/daemon.js

Fixes issue mentioned here #718

fix: correctly pass instanceId to daemon so scoping with controllerId works

---

charts/kubernetes-external-secrets/crds/kubernetes-client.io_externalsecrets_crd.yaml

This field is deprecated. fixes #773

fix: remove preserveUnknownFields

---

charts/kubernetes-external-secrets/templates/deployment.yaml
charts/kubernetes-external-secrets/values.yaml

Hi, I would like to add configuration which manages container security context in order to enhance container security.

feat(chart): add securityContext settings for `spec.containers[*].securityContext`

---

package-lock.json

fix(deps): update json-schema CVE-2021-3918
